# This file was adapted from work by Keith James (keithj)

sudo: required

language: perl

perl:
  - "5.16"
  - "5.22-shrplib"

env:
  global:
    - WTSI_NPG_GITHUB_URL=https://github.com/wtsi-npg
  matrix:
    - TRAVIS_NODE_VERSION="4.5.0"

before_install:
 - ./.travis/before_install_mysql57.sh
 - ./.travis/before_install.sh
install:
 - ./.travis/install.sh
script:
 - ./.travis/script.sh

